version: '2'
services:
  drone-daemon:
    image: drone/drone:0.8.1
    tty: true
    labels: 
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: drone-data-volume,drone-healthcheck,giddyup-volume
      io.rancher.scheduler.affinity:host_label: "{{.Values.host_affinity}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    volumes_from:
      - drone-data-volume
      - giddyup-volume
    environment:
      DEBUG: "{{.Values.debug_mode}}"
    {{- if ne .Values.database_service "false" }}
    external_links:
      - "{{.Values.database_service}}:database"{{- end }}
    entrypoint:
      - "/opt/rancher/bin/giddyup"
    command: ["exec", "--wait-for-file", "/etc/drone/dronerc", "--source-file", "/etc/drone/dronerc", "/drone", "server"]

  drone-healthcheck:
    image: rancher/giddyup:v0.19.0
    tty: true
    labels:
      io.rancher.container.pull_image: always
    network_mode: 'container:drone-daemon'
    command: "giddyup health"

  giddyup-volume:
    image: rancher/giddyup:v0.19.0
    network_mode: none
    labels:
      io.rancher.container.start_once: 'true'
    volumes_from:
      - drone-data-volume

  ## Do not change below. Could cause data loss in upgrade.
  drone-data-volume:
    image: busybox
    network_mode: none
    command: /bin/true
    labels:
      io.rancher.container.start_once: 'true'
    volumes:
      - /var/lib/drone
      - /etc/drone
